// lib/data/local/local_db.dart
//
// Hive local database bootstrap (offline-first).
// NOW includes:
// - meta box (string kv) for app flags (seed done, migrations, etc.)
// - automatic default seeding on first launch
//
// IMPORTANT: run build_runner to generate adapters:
// flutter pub run build_runner build --delete-conflicting-outputs

import 'package:hive_flutter/hive_flutter.dart';

import '../../models/account.dart';
import '../../models/budget.dart';
import '../../models/category.dart';
import '../../models/record.dart';
import 'seed_data.dart';

class LocalDb {
  static const String boxMeta = 'meta';
  static const String boxAccounts = 'accounts';
  static const String boxCategories = 'categories';
  static const String boxRecords = 'records';
  static const String boxBudgets = 'budgets';

  static bool _initialized = false;

  static Future<void> init() async {
    if (_initialized) return;

    await Hive.initFlutter();

    // Register adapters (generated by hive_generator)
    Hive.registerAdapter(AccountAdapter());
    Hive.registerAdapter(BudgetAdapter());
    Hive.registerAdapter(CategoryTypeAdapter());
    Hive.registerAdapter(CategoryAdapter());
    Hive.registerAdapter(RecordTypeAdapter());
    Hive.registerAdapter(RecordAdapter());

    // Open boxes
    await Hive.openBox<String>(boxMeta);
    await Hive.openBox<Account>(boxAccounts);
    await Hive.openBox<Category>(boxCategories);
    await Hive.openBox<Record>(boxRecords);
    await Hive.openBox<Budget>(boxBudgets);

    // Seed defaults once
    await SeedData.ensureSeeded();

    _initialized = true;
  }

  static Box<String> meta() => Hive.box<String>(boxMeta);

  static Box<Account> accounts() => Hive.box<Account>(boxAccounts);
  static Box<Category> categories() => Hive.box<Category>(boxCategories);
  static Box<Record> records() => Hive.box<Record>(boxRecords);
  static Box<Budget> budgets() => Hive.box<Budget>(boxBudgets);
}
